### PR TITLE
Unit test

### PR DESCRIPTION
**Pull request by Baroka-wp**
In this PR we implement the following :

- [x] Add unit tests to your classes:
- Book
- Person
- Student
- Teacher
- Classroom
- Rental
- all classes that you created while implementing the Decorator design pattern

### CODE REVIEW

**Review by RolandM99 — CHANGES_REQUESTED** [review]
### Hello Team , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly, make sure that you add the Gemfile in your project or you push it on Github when you pushed your project so that I could run locally your project and Test it as well. for now when I try to run `bundle install` to install all necessary `gems` to run your project I have this error below:
image
Not sure how to use Gemfile, you can take a look at this [documentation](https://bundler.io/v1.15/guides/bundler_setup.html) for more.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Rolandm99 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Baroka-wp** [comment]
## thank you @RolandM99 .

- [ ] Add Gemfile=> DONE 👌 

_Furthermore, I think it is possible to start the test directly with the `rspec` command in the terminal_

**Comment by RolandM99** [comment]
To run the test `rspec spec ` you have to add the gem for it. Great job by adding them.

**Review by Kingstalux — APPROVED** [review]
Hi @team,
# Status: Approved ✔️ ✔️ ✔️ 
 
179916932-7d4744b4-b79f-4bea-8082-aed7ac10b51e

## Highlights 👏 
✅ All tests are passing 🔥 
✅ Good commit history 👍 
✅ Linters are passing 👌 

Good job implementing the required changes 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
